// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXFiw74xmdKn0nDwfN682JFPYuMpJynio',
    appId: '1:501500294902:web:d8c8788d2b3a7d13909ed7',
    messagingSenderId: '501500294902',
    projectId: 'ahmedapp-2',
    authDomain: 'ahmedapp-2.firebaseapp.com',
    storageBucket: 'ahmedapp-2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG3V9P3KDpEc0thtTPVVEiOy01xO_EKVQ',
    appId: '1:501500294902:android:e3c9f29bdd951b9e909ed7',
    messagingSenderId: '501500294902',
    projectId: 'ahmedapp-2',
    storageBucket: 'ahmedapp-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrh_T0FFF2CzYSmNoQ3neJ3BppZ_cUuG8',
    appId: '1:501500294902:ios:cb805303530b3b07909ed7',
    messagingSenderId: '501500294902',
    projectId: 'ahmedapp-2',
    storageBucket: 'ahmedapp-2.appspot.com',
    iosBundleId: 'com.exm.fa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrh_T0FFF2CzYSmNoQ3neJ3BppZ_cUuG8',
    appId: '1:501500294902:ios:cb805303530b3b07909ed7',
    messagingSenderId: '501500294902',
    projectId: 'ahmedapp-2',
    storageBucket: 'ahmedapp-2.appspot.com',
    iosBundleId: 'com.exm.fa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXFiw74xmdKn0nDwfN682JFPYuMpJynio',
    appId: '1:501500294902:web:b7124687247e41b1909ed7',
    messagingSenderId: '501500294902',
    projectId: 'ahmedapp-2',
    authDomain: 'ahmedapp-2.firebaseapp.com',
    storageBucket: 'ahmedapp-2.appspot.com',
  );
}
